export const CALL_API_PENDING = "CALL_API_PENDING";

export const CREATE_TASK_FULFILLED = "CREATE_TASK_FULFILLED";
export const CREATE_TASK_REJECTED = "CREATE_TASK_REJECTED";

export const EDIT_TASK_FULFILLED = "EDIT_TASK_FULFILLED";
export const EDIT_TASK_REJECTED = "EDIT_TASK_REJECTED";

export const GET_LIST_TASKS_FULFILLED = "GET_LIST_TASKS_FULFILLED";
export const GET_LIST_TASKS_REJECTED = "GET_LIST_TASKS_REJECTED";

export const SET_EDIT_TASK_FULFILLED = "SET_EDIT_TASK_FULFILLED";
export const SET_EDIT_TASK_REJECTED = "SET_EDIT_TASK_REJECTED";

export const DELETE_TASK_FULFILLED = "DELETE_TASK_FULFILLED";
export const DELETE_TASK_REJECTED = "DELETE_TASK_REJECTED";

export const CHANGE_STATUS_TASK_FULFILLED = "CHANGE_STATUS_TASK_FULFILLED";
export const CHANGE_STATUS_TASK_REJECTED = "CHANGE_STATUS_TASK_REJECTED";

export const CHANGE_SEARCH_FILTER = "CHANGE_SEARCH_FILTER";

export const GET_LIST_USERS_FULFILLED = "GET_LIST_USERS_FULFILLED";
