export const SUBMIT_FORM_PENDING = "SUBMIT_FORM_PENDING";
export const SUBMIT_FORM_REJECTED = "SUBMIT_FORM_REJECTED";
export const OPEN_FORM_CREATE = "OPEN_FORM_CREATE";
export const CLOSE_FORM_CREATE = "CLOSE_FORM_CREATE";
export const SUBMIT_FORM_CREATE_FULFILLED = "SUBMIT_FORM_CREATE_FULFILLED";
export const SUBMIT_FORM_EDIT_FULFILLED = "SUBMIT_FORM_EDIT_FULFILLED";

export const SET_EDIT_TASK = "SET_EDIT_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_ITEM";
export const CHANGE_STATUS_TASK = "CHANGE_STATUS_TASK";
export const CHANGE_ACTIVE_TASK = "CHANGE_ACTIVE_TASK";
export const CHANGE_SEARCH_FILTER = "CHANGE_SEARCH_FILTER";
