export const NEXT_STEP_FORM = "NEXT_STEP_FORM";
export const BACK_STEP_FORM = "BACK_STEP_FORM";
export const CHANGE_VALUE_FORM = "CHANGE_VALUE_FORM";
export const CHANGE_ERROR_MESSAGE = "CHANGE_ERROR_MESSAGE";

export const SUBMIT_FORM_PENDING = "SUBMIT_FORM_PENDING";
export const SUBMIT_FORM_FULFILLED = "SUBMIT_FORM_FULFILLED";
export const SUBMIT_FORM_REJECTED = "SUBMIT_FORM_REJECTED";
